# Generated by Django 4.1.1 on 2022-11-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_date_task_deadline_lineitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='job',
        ),
        migrations.RemoveField(
            model_name='person',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='person',
            field=models.ManyToManyField(to='events.person'),
        ),
    ]
