# Generated by Django 4.1.1 on 2022-11-14 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_person_job_remove_person_task_task_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='person',
        ),
        migrations.AddField(
            model_name='task',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.person'),
        ),
    ]
