# Generated by Django 4.1.1 on 2022-11-29 11:08

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_created_at_event_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.datetime.today().timestamp())]),
        ),
    ]
