# Generated by Django 4.1.1 on 2022-11-29 19:55

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date.today)]),
        ),
    ]
