# Generated by Django 4.1.1 on 2022-12-01 17:13

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0016_remove_event_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredevent',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.date.today, null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date.today)]),
        ),
    ]
