# Generated by Django 4.1.1 on 2022-12-04 21:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.date.today, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date.today)]),
        ),
    ]
