# Generated by Django 4.1.1 on 2022-12-05 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_alter_task_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredevent',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
