# Generated by Django 4.1.1 on 2022-12-05 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_alter_registeredevent_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='publish',
            field=models.BooleanField(default=False, validators=[datetime.date]),
        ),
    ]
