# Generated by Django 4.1.1 on 2022-12-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_alter_event_publish'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_title_aedf91_idx',
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['author'], name='events_even_author__10d1c2_idx'),
        ),
    ]
