# Generated by Django 4.1.1 on 2022-12-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_remove_event_events_even_title_aedf91_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
